import type { Metadata } from "next";
// Importa o componente Script do Next.js para carregar scripts externos
import Script from 'next/script'; 
import { GoogleAnalytics } from "@next/third-parties/google"; 
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Seu ID do AdSense (para referência)
const ADSENSE_PUB_ID = 'ca-pub-9532990788495378';

// Seu ID do Google Analytics
const GA_MEASUREMENT_ID = 'G-BZ5KYMZ57L'; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// A tag de verificação do AdSense é inserida automaticamente
// no <head> com esta configuração de Metadata.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    // 1. Tag de verificação do site AdSense
    'google-adsense-account': ADSENSE_PUB_ID,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 2. Script principal do AdSense para ativar os Anúncios Automáticos */}
      <Script
        async 
        src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${ADSENSE_PUB_ID}`}
        crossOrigin="anonymous"
        strategy="afterInteractive" // Garante que o script é carregado após a interação
      />

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      
      {/* Google Analytics continua aqui */}
      <GoogleAnalytics gaId={GA_MEASUREMENT_ID} /> 

    </html>
  );
}